server:
  port: 8080

management:
  context-path: /mgmt

spring:
  boot:
    admin:
      url: http://localhost:8080
  application:
    name: admin-server
  aop:
    proxy-target-class: true
    
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8081/uaa/oauth/token
      userAuthorizationUri: http://localhost:8081/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:8081/uaa/user
      
logging:
  level:
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG
